export const REGEX = {
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  URL: /^(https?:\/\/)?([\w.-]+)\.([a-z]{2,})([\/\w .-]*)*\/?$/,
  TEL: /^0\d{1,4}-\d{1,4}-\d{4}$/,
  POSTAL_CODE: /^\d{3}-\d{4}$/,
  DATE: /^\d{4}-\d{2}-\d{2}$/,
  TIME: /^([01]\d|2[0-3]):([0-5]\d)$/,
  DATETIME: /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/,
  COLOR_CODE: /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
  USERNAME: /^[a-zA-Z0-9_-]+$/,
  ALPHANUMERIC: /^[a-zA-Z0-9]+$/,
  DIGIT: /^\d+$/,
  HIRAGANA: /^[ぁ-んー　]+$/,
  KATAKANA: /^[ァ-ヶー　]+$/,
  STRONG_PASSWORD: {
    UPPER: /[A-Z]/,
    LOWER: /[a-z]/,
    DIGIT: /[0-9]/,
    SYMBOL: /[!@#$%^&*(),.?":{}|<>_\-]/,
  },
  FILE_EXTENSION: /\.[0-9a-z]+$/i,
}
